# Algebra liniowa
## Wektory i wartości własne

**Rozkład macierzy**

Rozkład macierzy to przywrócenie jej do czynników pierwszych. Tak, jak robimy to w przypadku indywidualnych liczb. Np. weźmy liczbę 15. Jej czynniki pierwsze to 3 i 5. 

Rozkłady macierzy są pomocne w poszukiwaniu macierzy odwrotnych, czy obliczania wyznaczników. Z pomocą metodą rozkładu macierzy, zwanej **rozkładem własnym**, możemy dokonać analizy głónych składowych np. w uczeniu maszynowym. 

Poprzez dzielenie macierzy (kwadratowych) na składniki, możemy łatwiej pracować z nimi z problemach ML. W przypadku rozkładu własnego używamy dwóch składników: 
* wartość własna $\lambda$
* wektora własnego $v$.


In [21]:
import numpy as np
from numpy import array, diag
from numpy.linalg import eig
from sympy import *
from numpy.linalg import inv
import matplotlib.pyplot as plt

In [2]:
A = np.array([
    [1,2],
    [4,5]
])
wartosci_wlasne, wektor_wlasny = eig(A)
wartosci_wlasne,wektor_wlasny

(array([-0.46410162,  6.46410162]),
 array([[-0.80689822, -0.34372377],
        [ 0.59069049, -0.9390708 ]]))

Możemy również zbudować macierz pierwotną z wartosci wlasnych i wektora wlasnego, wg następującego wzoru:

$Av = \lambda v$

Wyprowadzamy A i przekształcamy równanie:

$A = Q* Q_neg1* Q - 1$

Gdzie Q to wektory własne, a Q negative 1 to wartosci wlasne w postaci diagonalnej (odwrotna macierz Q). 

In [3]:
Q = wektor_wlasny
R = inv(Q)
L = diag(wartosci_wlasne)
B = Q @ L @ R
B

array([[1., 2.],
       [4., 5.]])

Więcej na playliscie - Essence of linear Algebra https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab

##  Ćwiczenia

Wektor v ma wartosc 1,2, ale następnie przechodzi do przekształcenie. Wektor i przesuwa się do punktu 2,0, a wektor j przesuwa się do punktu 0,1.5. Gdzie przesuwa się wektor v?

In [4]:
v = np.array([1,2])
i = np.array([2,0])
j = np.array([0, 1.5])

In [5]:
baza = array([i,j])
baza

array([[2. , 0. ],
       [0. , 1.5]])

In [6]:
v_new = baza @ v
v_new

array([2., 3.])

Wektor v ma wartosc 1,2,, ale nastepnie przechodzi do przeksztalcenia. Wektor i przesuwa się do punktu -2,1, a wektor j przesuwa się do punktu 1,-2. Gdzie przesuwa się wektor v?

In [7]:
v = np.array([1,2])
i = np.array([-2,1])
j = np.array([1, -2])

In [8]:
baza = array([i,j])
baza

array([[-2,  1],
       [ 1, -2]])

In [9]:
v_new = baza @ v
v_new

array([ 0, -3])

Przeksztalcenie przesuwa wektor i do punktu 1,0, a wektor j do punktu 2,2. Jaki jest wyznacznik tego przekształcenia?

In [10]:
# Czyli musimy odpowiedziec na pytanie jak zmieniło sie pole obszaru po wykonaniu przeksztalcenia

from numpy.linalg import det

i = array([1,0])
j = array([2,2])

baza = array([i,j]).T
det(baza)

2.0

Czy dwa lub więcej przekształeń liniowych można przeprowadzić w ramach jednego przekształcenia liniowego. Dlaczego tak albo dlaczego nie?

Tak, poniważ możemy przkeształcenia zagregować do matrycy.

Rozwiąż układ równań z niewiadomymi x,y,z:

$
3x + 1y + 0z = 54
$

$
2x + 4y + 1z = 12
$

$
3x + 1y + 8z = 6
$

In [11]:
# Czyli dzielimy sobie ten uklad
# na matryce
# W matrycy A umieszczamy coefficients do
# niewiadomych
A = array ([
    [3,1,0],
    [2,4,1],
    [3,1,8]
])

A



array([[3, 1, 0],
       [2, 4, 1],
       [3, 1, 8]])

In [12]:
# W matrycy B umieszczamy wartosci po prawej stronie
B = array([
    54,12,6])
B

array([54, 12,  6])

In [16]:
#Obliczamy odwrotnosc macierzy A
A_inv = inv(A)
A_inv

array([[ 0.3875, -0.1   ,  0.0125],
       [-0.1625,  0.3   , -0.0375],
       [-0.125 ,  0.    ,  0.125 ]])

In [19]:
# Mnozymy macierz odwrotna A przez B
A_inv.dot(B)

array([19.8, -5.4, -6. ])

Czy ponizsza macierz jest liniowa zalezna? Dlaczego tak albo dlaczego nie?

In [29]:
baza = Matrix([
    [2,1],
    [6,3]
])
baza

Matrix([
[2, 1],
[6, 3]])

In [30]:
wyznacznik = det(baza)
wyznacznik

0

Ponizsza macierz jest liniowa zalezna, poniewaz jej wyznacznik jest równy zero.