# Algerba liniowa
## Rodzaje macierzy

### Macierz kwadratowa

Macierz o równej liczbie kolumn i wierszy. Wykorzystywana do reprezentowania przekształceń liniowych .

In [8]:
import numpy as np
from sympy import *
np.array([[1,2], [2,1]])

array([[1, 2],
       [2, 1]])

### Macierz jednostkowa
Przekątna macierzy jednostkowej (tożsamościowej) zawiera same jedynki, a pozostałe wartości macierzy są równe zeru. Mają duże znacznie przy rozwiązywanie układów równań.

In [2]:
np.array ([[1,0,0], [0,1,0], [0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Macierz odwrotna
Macierz odwrotna odwaraca przekształcenia zdefiniowane przez inną macierz.

In [3]:
a = np.array([[4,2,4], [5,3,7], [9,3,6]])
a

array([[4, 2, 4],
       [5, 3, 7],
       [9, 3, 6]])

In [4]:
a_neg = np.array([[-0.5, 0,1/3], [5.5, -2, 4/3], [-2, 1, 1/3]])
a_neg

array([[-0.5       ,  0.        ,  0.33333333],
       [ 5.5       , -2.        ,  1.33333333],
       [-2.        ,  1.        ,  0.33333333]])

Macierz odwrotną dla macierzy A jesteśmy w stanie obliczyć z pomocą numpy/sympy.

Gdy pomnożymy macierz odwrotną przez macierz a, otrzymamy macierz jednostkową. 

In [9]:
A = Matrix([
    [4,2,4],
    [5,3,7],
    [9,3,6]
])

In [11]:
odwrotna_A = A.inv()
odwrotna_A

Matrix([
[-1/2,  0,  1/3],
[11/2, -2, -4/3],
[  -2,  1,  1/3]])

In [14]:
jednostkowa = odwrotna_A * A
jednostkowa

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

### Macierz diagonalna

Idea macierzy diagonalnej jest podobna do macierzy jednostkowej. Z tym wyjątkiem, że w przypadku macierzy diagonalnej wartości poprzekątnej są różne od 1. 

In [15]:
diag = Matrix([
    [4,0,0],
    [0,2,0],
    [0,0,5]])
diag

Matrix([
[4, 0, 0],
[0, 2, 0],
[0, 0, 5]])

### Macierz trójkątna
W przypadku macierzy trójkątnej, wszystkie wartości po przekątnej są niezerowe. A wszystkie wartości pod lub nad tą przekątną są równe zeru. 

In [20]:
triangle = Matrix([
    [4,1,3],
    [0,2,4],
    [0,0,5]])
triangle

Matrix([
[4, 1, 3],
[0, 2, 4],
[0, 0, 5]])

### Macierz rzadka
Macierze rzadkie (rzadko spotykane) mają niewiele elementów niezerowych. Mogą być wykorzystywane do zwiększenia efektywności - poprzez śledzenie jedynie elemnentów niezerowych.

In [22]:
rare = Matrix([
    [0,0,0],
    [0,2,0],
    [0,0,0]])
rare

Matrix([
[0, 0, 0],
[0, 2, 0],
[0, 0, 0]])