# Algebra liniowa
## Wektory i wartości własne

**Rozkład macierzy**

Rozkład macierzy to przywrócenie jej do czynników pierwszych. Tak, jak robimy to w przypadku indywidualnych liczb. Np. weźmy liczbę 15. Jej czynniki pierwsze to 3 i 5. 

Rozkłady macierzy są pomocne w poszukiwaniu macierzy odwrotnych, czy obliczania wyznaczników. Z pomocą metodą rozkładu macierzy, zwanej **rozkładem własnym**, możemy dokonać analizy głónych składowych np. w uczeniu maszynowym. 

Poprzez dzielenie macierzy (kwadratowych) na składniki, możemy łatwiej pracować z nimi z problemach ML. W przypadku rozkładu własnego używamy dwóch składników: 
* wartość własna $\lambda$
* wektora własnego $v$.


In [5]:
from numpy import array, diag
from numpy.linalg import eig, inv

In [3]:
A = np.array([
    [1,2],
    [4,5]
])
wartosci_wlasne, wektor_wlasny = eig(A)
wartosci_wlasne,wektor_wlasny

(array([-0.46410162,  6.46410162]),
 array([[-0.80689822, -0.34372377],
        [ 0.59069049, -0.9390708 ]]))

Możemy również zbudować macierz pierwotną z wartosci wlasnych i wektora wlasnego, wg następującego wzoru:

$Av = \lambda v$

Wyprowadzamy A i przekształcamy równanie:

$A = Q* Q_neg1* Q - 1$

Gdzie Q to wektory własne, a Q negative 1 to wartosci wlasne w postaci diagonalnej (odwrotna macierz Q). 

In [6]:
Q = wektor_wlasny
R = inv(Q)
L = diag(wartosci_wlasne)
B = Q @ L @ R
B

array([[1., 2.],
       [4., 5.]])

Więcej na playliscie - Essence of linear Algebra https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab